server:
  port: 8080

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:migrations/master.yml
